### ISSUE TITLE
create js bot functionality template

### ISSUE THREAD

**Issue by Lane-G-Smith** [Lane-G-Smith/AI-Personalities-React-App#10]
This should serve as the javascript needed to make the API calls to OpenAI and send the responses to the page. GPT-model, personality logic, Q@A lines in the API call, and the JSON response should be variables so they can be interchanged with the data from the database. Descriptions can be found on the OpenAI documentation page. https://platform.openai.com/docs/api-reference/making-requests

**Comment by akpi816218** [comment]
Fixed by #23
